/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ejercicio2;

/**
 *
 * @author ADMIN
 */
public class Ejercicio2 extends javax.swing.JFrame {

    /**
     * Creates new form Ejercicio2
     */
    public Ejercicio2() {
        initComponents();
        this.setTitle("Imitador");
        this.setLocation(500,100);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoOriginal = new javax.swing.ButtonGroup();
        grupoEspejo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rbOriginal1 = new javax.swing.JRadioButton();
        rbOriginal2 = new javax.swing.JRadioButton();
        rbOriginal3 = new javax.swing.JRadioButton();
        rbEspejo1 = new javax.swing.JRadioButton();
        rbEspejo2 = new javax.swing.JRadioButton();
        rbEspejo3 = new javax.swing.JRadioButton();
        cOriginal1 = new javax.swing.JCheckBox();
        cOriginal2 = new javax.swing.JCheckBox();
        cOriginal3 = new javax.swing.JCheckBox();
        cEspejo1 = new javax.swing.JCheckBox();
        cEspejo2 = new javax.swing.JCheckBox();
        cEspejo3 = new javax.swing.JCheckBox();
        fieldOriginal = new javax.swing.JTextField();
        fieldEspejo = new javax.swing.JTextField();
        boxOriginal = new javax.swing.JComboBox<>();
        boxEspejo = new javax.swing.JComboBox<>();
        spinnerOriginal = new javax.swing.JSpinner();
        spinnerEspejo = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Original");

        jLabel2.setText("Espejo");

        grupoOriginal.add(rbOriginal1);
        rbOriginal1.setText("Opcion 1");
        rbOriginal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbOriginal1ActionPerformed(evt);
            }
        });

        grupoOriginal.add(rbOriginal2);
        rbOriginal2.setText("Opcion 2");
        rbOriginal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbOriginal2ActionPerformed(evt);
            }
        });

        grupoOriginal.add(rbOriginal3);
        rbOriginal3.setText("Opcion 3");
        rbOriginal3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbOriginal3ActionPerformed(evt);
            }
        });

        grupoEspejo.add(rbEspejo1);
        rbEspejo1.setText("Opcion 1");
        rbEspejo1.setEnabled(false);
        rbEspejo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbEspejo1ActionPerformed(evt);
            }
        });

        grupoEspejo.add(rbEspejo2);
        rbEspejo2.setText("Opcion 2");
        rbEspejo2.setEnabled(false);

        grupoEspejo.add(rbEspejo3);
        rbEspejo3.setText("Opcion 3");
        rbEspejo3.setEnabled(false);

        cOriginal1.setText("Opcion 4");
        cOriginal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cOriginal1ActionPerformed(evt);
            }
        });

        cOriginal2.setText("Opcion 5");
        cOriginal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cOriginal2ActionPerformed(evt);
            }
        });

        cOriginal3.setText("Opcion 6");
        cOriginal3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cOriginal3ActionPerformed(evt);
            }
        });

        cEspejo1.setText("Opcion 4");
        cEspejo1.setEnabled(false);

        cEspejo2.setText("Opcion 5");
        cEspejo2.setEnabled(false);

        cEspejo3.setText("Opcion 6");
        cEspejo3.setEnabled(false);

        fieldOriginal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fieldOriginalKeyTyped(evt);
            }
        });

        fieldEspejo.setEnabled(false);

        boxOriginal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        boxOriginal.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                boxOriginalItemStateChanged(evt);
            }
        });

        boxEspejo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        boxEspejo.setEnabled(false);

        spinnerOriginal.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerOriginalStateChanged(evt);
            }
        });

        spinnerEspejo.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(rbOriginal3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cOriginal3))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rbOriginal2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cOriginal2))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rbOriginal1)
                                        .addGap(46, 46, 46)
                                        .addComponent(cOriginal1)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(boxOriginal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldOriginal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spinnerOriginal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbEspejo1)
                            .addComponent(rbEspejo2)
                            .addComponent(jLabel2)
                            .addComponent(rbEspejo3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cEspejo2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cEspejo3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cEspejo1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(69, 69, 69)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(boxEspejo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(spinnerEspejo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(fieldEspejo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbOriginal1)
                    .addComponent(cOriginal1)
                    .addComponent(fieldOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbOriginal2)
                    .addComponent(cOriginal2)
                    .addComponent(boxOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbOriginal3)
                    .addComponent(cOriginal3)
                    .addComponent(spinnerOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbEspejo1)
                    .addComponent(cEspejo1)
                    .addComponent(fieldEspejo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbEspejo2)
                    .addComponent(cEspejo2)
                    .addComponent(boxEspejo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbEspejo3)
                    .addComponent(cEspejo3)
                    .addComponent(spinnerEspejo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbOriginal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbOriginal1ActionPerformed
        this.rbEspejo1.setSelected(this.rbOriginal1.isSelected());
    }//GEN-LAST:event_rbOriginal1ActionPerformed

    private void rbEspejo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbEspejo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbEspejo1ActionPerformed

    private void rbOriginal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbOriginal2ActionPerformed
        this.rbEspejo2.setSelected(this.rbOriginal2.isSelected());
    }//GEN-LAST:event_rbOriginal2ActionPerformed

    private void rbOriginal3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbOriginal3ActionPerformed
        this.rbEspejo3.setSelected(this.rbOriginal3.isSelected());
    }//GEN-LAST:event_rbOriginal3ActionPerformed

    private void cOriginal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cOriginal1ActionPerformed
        this.cEspejo1.setSelected(this.cOriginal1.isSelected());
    }//GEN-LAST:event_cOriginal1ActionPerformed

    private void cOriginal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cOriginal2ActionPerformed
        this.cEspejo2.setSelected(this.cOriginal2.isSelected());
    }//GEN-LAST:event_cOriginal2ActionPerformed

    private void cOriginal3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cOriginal3ActionPerformed
         this.cEspejo3.setSelected(this.cOriginal3.isSelected());
    }//GEN-LAST:event_cOriginal3ActionPerformed

    private void fieldOriginalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldOriginalKeyTyped
        this.fieldEspejo.setText(this.fieldOriginal.getText());
    }//GEN-LAST:event_fieldOriginalKeyTyped

    private void boxOriginalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_boxOriginalItemStateChanged
        this.boxEspejo.setSelectedIndex(this.boxOriginal.getSelectedIndex());
    }//GEN-LAST:event_boxOriginalItemStateChanged

    private void spinnerOriginalStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerOriginalStateChanged
       this.spinnerEspejo.setValue(this.spinnerOriginal.getValue());
    }//GEN-LAST:event_spinnerOriginalStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxEspejo;
    private javax.swing.JComboBox<String> boxOriginal;
    private javax.swing.JCheckBox cEspejo1;
    private javax.swing.JCheckBox cEspejo2;
    private javax.swing.JCheckBox cEspejo3;
    private javax.swing.JCheckBox cOriginal1;
    private javax.swing.JCheckBox cOriginal2;
    private javax.swing.JCheckBox cOriginal3;
    private javax.swing.JTextField fieldEspejo;
    private javax.swing.JTextField fieldOriginal;
    private javax.swing.ButtonGroup grupoEspejo;
    private javax.swing.ButtonGroup grupoOriginal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton rbEspejo1;
    private javax.swing.JRadioButton rbEspejo2;
    private javax.swing.JRadioButton rbEspejo3;
    private javax.swing.JRadioButton rbOriginal1;
    private javax.swing.JRadioButton rbOriginal2;
    private javax.swing.JRadioButton rbOriginal3;
    private javax.swing.JSpinner spinnerEspejo;
    private javax.swing.JSpinner spinnerOriginal;
    // End of variables declaration//GEN-END:variables
}
