/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ejercicio3;

import java.io.*;
import java.util.StringJoiner;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 Kingston A2000/Disco solido M.2 NVME de alta velocidad/129.99
MVD Blue SN550/Disco solido M.2 NVME de alta velocidad/99.99
SanDisk Extreme Pro/Disco solido USB 3.2 Gen 2 externo/309.9
 */
public class Ejercicio3 extends javax.swing.JFrame {

    /**
     * Creates new form Ejercicio3
     */
    public Ejercicio3() {
        
        initComponents();
        this.setTitle("Lista de productos");
        this.setLocation(500,100);
        this.setResizable(false);
        
        modelo = new DefaultTableModel();
        this.tabla.setModel(modelo);
        
        modelo.addColumn("Nombre");
        modelo.addColumn("Descripcion");
        modelo.addColumn("Precio");
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        buscarArchivo = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();
        importar = new javax.swing.JButton();
        botonCambios = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Descripcion", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla.getTableHeader().setResizingAllowed(false);
        tabla.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabla);
        if (tabla.getColumnModel().getColumnCount() > 0) {
            tabla.getColumnModel().getColumn(0).setResizable(false);
            tabla.getColumnModel().getColumn(1).setResizable(false);
            tabla.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel1.setText("Seleccione un archivo txt");

        buscarArchivo.setEnabled(false);

        buscar.setText("...");
        buscar.setToolTipText("Examinar archivos");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        importar.setText("Importar datos de txt");
        importar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importarActionPerformed(evt);
            }
        });

        botonCambios.setText("Guardar cambios");
        botonCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCambiosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonCambios)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(buscarArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(importar)
                        .addComponent(jLabel1)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(importar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonCambios)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void importarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importarActionPerformed
        //Evento para cargar los datos del archivo.txt a la tabla
        
       archivo = new File(buscarArchivo.getText());
       
       try{
           fr= new FileReader(archivo);
           buffer = new BufferedReader(fr);
           tabla.getModel();
           Object[] linea = buffer.lines().toArray();
           
           for(int i=0; i<linea.length;i++){
               String[] fila = linea[i].toString().split("/");
               modelo.addRow(fila);
               buffer.close();
               fr.close();
           }
       }catch(Exception ex){
           
       }
        
       
    }//GEN-LAST:event_importarActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
       //Evento que determinara que ocurrira cuando se pulse el boton buscar
       
       //Creamos una instancia de JFileChooser
       JFileChooser seleccion = new JFileChooser();
       
       //Escribimos el nombre del titulo
       seleccion.setDialogTitle("Elige un archivo");
       
       //Indicamos que solo se pueden elegir ficheros
       seleccion.setFileSelectionMode(JFileChooser.FILES_ONLY);
       
       //Creamos un filtro txt
       FileNameExtensionFilter filtro = new FileNameExtensionFilter("*.txt", "txt");
       seleccion.setFileFilter(filtro);
       
       int eleccion = seleccion.showOpenDialog(this);
       if(eleccion == JFileChooser.APPROVE_OPTION){
           buscarArchivo.setText(seleccion.getSelectedFile().getPath());
       }
       
       
        
    }//GEN-LAST:event_buscarActionPerformed

    private void botonCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCambiosActionPerformed
        // Evento que permitira guardar los cambios de precios que se realicen en la tabla en el archivo txt
       archivo = new File(buscarArchivo.getText());
       tabla.getModel();
       
       
       //Limpia el archivo.txt
       try{
           PrintWriter pw= new PrintWriter(archivo);
           pw.print("");
           pw.close();

       }catch(Exception ex){
           JOptionPane.showMessageDialog(null, "Ocurrio un problema" + ex.toString());
       }
       
       //Guarda en el archivo.txt los nuevos registros
       
       try{
           fw = new FileWriter(archivo);
           bw = new BufferedWriter(fw);

           for(int i=0;i< tabla.getRowCount(); i++){
               StringJoiner joiner = new StringJoiner("/");
               for(int j=0;j<tabla.getColumnCount();j++){
                   Object obj = tabla.getValueAt(i, j);
                   String valor = obj == null ? "null" :obj.toString();
                   joiner.add(valor);
               }
               System.out.println(joiner.toString());
               bw.write(joiner.toString());
               bw.newLine(); //inserta nueva linea.
           }
          
               bw.close();
               fw.close();
           JOptionPane.showMessageDialog((JButton) evt.getSource(), "Los cambios se realizaron correctamente", "Guardar cambios", JOptionPane.INFORMATION_MESSAGE);
       }catch(Exception ex){
           JOptionPane.showMessageDialog(null, "Ocurrio un error", "Error al guardar los cambios", JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_botonCambiosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio3().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCambios;
    private javax.swing.JButton buscar;
    private javax.swing.JTextField buscarArchivo;
    private javax.swing.JButton importar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
    private DefaultTableModel modelo;
    private File archivo;
    private BufferedReader buffer;
    private FileReader fr;
    private BufferedWriter bw;
    private FileWriter fw;
    
    
   
    
    
}
